const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
    {
    id: 2,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/w/n/z/9-gld-039-beonza-white-original-imah67y8zemucsam.jpeg?q=70",
    title: "Air Max Zoom",
    reviews: "(84 reviews)",
    prevPrice: "$170.00",
    newPrice: "200",
    company: "Adidas",
    color: "white",
    category: "sandals"
  },
  {
    id:3,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/6/f/d/6-casual-24501-6-nobelite-white-green-original-imahd7j3xmfbhghx.jpeg?q=70",
    title: "Nike Waffle One Sneaker",
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    id:4,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/u/8/s/10-nk-1003-black-10-10-nekso-black-original-imah7fxywr7nnsed.jpeg?q=70",
    title: "Nike Running Shoe",
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
    {
    id: 5,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/v/k/v/7-blue-7-brk-footwear-blue-original-imahd2p5hktnmezd.jpeg?q=70",
    title: "Street Style Low",
    reviews: "(199 reviews)",
    prevPrice: "$155.00",
    newPrice: "100",
    company: "Nike",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 6,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/l/v/3/8-summerbloom-sndl-15-white-8-0-sb-summerbloom-white-original-imahcv7ejcf2un6w.jpeg?q=70",
    title: "Women Heels",
    reviews: "(204 reviews)",
    prevPrice: "$141.00",
    newPrice: "200",
    company: "Puma",
    color: "white",
    category: "heels"
  },
  {
    id: 7,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/s/b/u/9-pista-09-luxyfeel-pista-original-imaggqfhsgvrrkvh.jpeg?q=70",
    title: "Wave Horizon",
    reviews: "(116 reviews)",
    prevPrice: "$138.00",
    newPrice: "50",
    company: "Vans",
    color: "green",
    category: "flats"
  },
  {
    id: 8,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/f/j/t/6-sparxsm323-6-sparx-black1-original-imah9vff6guq8tht.jpeg?q=70",
    title: "Classic Court",
    reviews: "(98 reviews)",
    prevPrice: "$160.00",
    newPrice: "150",
    company: "Nike",
    color: "black",
    category: "heels"
  },
  {
    id: 9,
    img: "https://rukminim2.flixcart.com/image/612/612/kt8zb0w0/sandal/r/z/z/9-dex-01-r-blue-9-density-r-blue-original-imag6n3ym5ketnef.jpeg?q=70",
    title: "Infinity React",
    reviews: "(221 reviews)",
    prevPrice: "$145.00",
    newPrice: "100",
    company: "Adidas",
    color: "blue",
    category: "sandals"
  },
  {
    id: 10,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-sandal/0/l/p/8-canvas-01-8-flipjones-white-original-imah8wqbu92ueghk.jpeg?q=70",
    title: "Slip-On Comfort",
    reviews: "(176 reviews)",
    prevPrice: "$134.00",
    newPrice: "50",
    company: "Puma",
    color: "white",
    category: "sandals"
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Retro Super Future",
    reviews: "(162 reviews)",
    prevPrice: "$188.00",
    newPrice: "100",
    company: "Adidas",
    color: "red",
    category: "sneakers"
  },
    {
    img: "https://rukminim2.flixcart.com/image/612/612/jy4q3680/shoe/s/t/j/sega5bkrdph-6-segastar-black-original-imafdhjkfmmd8k3g.jpeg?q=70",
    title: "Nike Air Vapormax Plus",
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },
  {
    id: 13,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/o/p/b/8-sport-x-men-8-xdox-navy-blue-original-imaggwxtvrkzhfhq.jpeg?q=70",
    title: "Men Sports Sandal",
    reviews: "(145 reviews)",
    prevPrice: "$130.00",
    newPrice: "50",
    company: "Puma",
    color: "red",
    category: "sandals"
  },
  {
    id: 14,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/0/j/y/6-611-white-6-pu-pine-white-original-imahd9bhtcuvyqhq.jpeg?q=70",
    title: "ZoomX Vaporfly",
    reviews: "(112 reviews)",
    prevPrice: "$149.00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals"
  },
  {
    id: 15,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/w/w/k/6-bbmh9073-6-bacca-bucci-black-original-imah3fv84nvms5ay.jpeg?q=70",
    title: "bacca bucci",
    reviews: "(276 reviews)",
    prevPrice: "$180.00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "heels"
  },
  {
    id: 16,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-sandal/y/q/8/6-454-6-density-black-red-original-imahfzgfhrzhhr2k.jpeg?q=70",
    title: "Bandana Slip",
    reviews: "(203 reviews)",
    prevPrice: "$120.00",
    newPrice: "60",
    company: "Nike",
    color: "red",
    category: "sandals"
  },
  {
    id: 17,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/n/h/a/2-2424-35-klaur-melbourne-red-original-imagzndcbzzbetqu.jpeg?q=70",
    title: "Stiletto Glam",
    reviews: "(322 reviews)",
    prevPrice: "$220.00",
    newPrice: "180",
    company: "Adidas",
    color: "red",
    category: "heels"
  },
  {
    id: 18,
    title: "VaporFly",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/c/7/j/12-ca4510-12-kraasa-blue-original-imagjfgrb3tjgrxe.jpeg?q=70",
    reviews: "(114 reviews)",
    prevPrice: "$155.00",
    newPrice: "130",
    company: "Nike",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 20,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/g/n/r/9-cross-05-9-ravis-green-original-imah5yhz7ed5hmxk.jpeg?q=70",
    title: "Dream Ballet Flats",
    reviews: "(98 reviews)",
    prevPrice: "$90.00",
    newPrice: "70",
    company: "Vans",
    color: "green",
    category: "flats"
  },
  {
    id: 21,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/3/a/1/9-casual-24514-9-nobelite-white-blue-original-imahdyz7ndtzf6gp.jpeg?q=70",
    title: "Nova Blaze Sneaker",
    reviews: "(144 reviews)",
    prevPrice: "$132.00",
    newPrice: "90",
    company: "Nike",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 22,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/z/l/i/5-dm-90-3-royty-red-original-imahcfpvwdszjnue.jpeg?q=70",
    title: "Women Heels Sandal",
    reviews: "(129 reviews)",
    prevPrice: "$140.00",
    newPrice: "110",
    company: "Puma",
    color: "red",
    category: "heels"
  },
  {
    id: 23,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/o/i/t/10-xo-soldier-12-blue-gry-10-fuel-blue-original-imah9zkmfqgcygks.jpeg?q=70",
    title: "Comet Flex Sandals",
    reviews: "(312 reviews)",
    prevPrice: "$158.00",
    newPrice: "140",
    company: "Vans",
    color: "blue",
    category: "sandals"
  },
  {
    id: 25,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/f/v/2/8-boston-01-8-asian-dark-grey-black-original-imah3wr6yb3qahng.jpeg?q=70",
    title: "Boston-01 Chunky Sneakers",
    reviews: "(201 reviews)",
    prevPrice: "$175.00",
    newPrice: "155",
    company: "Nike",
    color: "black",
    category: "heels"
  },
  {
    id: 26,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/g/l/t/6-509j-red-commander-red-original-imaghxh4uu22q2sm.jpeg?q=70",
    title: "Echo Edge Heels",
    reviews: "(188 reviews)",
    prevPrice: "$160.00",
    newPrice: "120",
    company: "Vans",
    color: "red",
    category: "heels"
  },
  {
    id: 27,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/8/c/d/9-2fd-vador-blu-u-s-polo-assn-dk-blue-original-imagxpg8cmmczugh.jpeg?q=70",
    title: "Flyknit Free Runs",
    reviews: "(174 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Puma",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 29,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/m/o/t/7-119-light-green-26-5-sharansh-gallery-light-green-original-imagsw53kuqdstjy.jpeg?q=70",
    title: "EasyWear SlipOns",
    reviews: "(210 reviews)",
    prevPrice: "$115.00",
    newPrice: "90",
    company: "Vans",
    color: "green",
    category: "flats"
  },
  {
    id: 30,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/j/s/z/6-rng-eva-842-blk-6-bruton-black-original-imah364qusfdnhj5.jpeg?q=70",
    title: "BRUTON",
    reviews: "(126 reviews)",
    prevPrice: "$130.00",
    newPrice: "100",
    company: "Nike",
    color: "black",
    category: "sandals"
  },
  {
    id: 31,
    img: "https://rukminim2.flixcart.com/image/612/612/kf0087k0-0/shoe/z/6/q/hc22509-44-m7-by-metronaut-blue-original-imafvjsg8v9ef2gt.jpeg?q=70",
    title: "Velocity Knit #31",
    reviews: "(234 reviews)",
    prevPrice: "$160.00",
    newPrice: "130",
    company: "Puma",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 32,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/p/p/p/6-san3-red-6-0-parx-enterprises-red-original-imahdydmszjeqf3h.jpeg?q=70",
    title: "Lite Sport Mesh",
    reviews: "(118 reviews)",
    prevPrice: "$110.00",
    newPrice: "85",
    company: "Nike",
    color: "red",
    category: "sandals"
  },
  {
    id: 33,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/f/j/z/8-vy-rd-031-green-8-deera-green-original-imah72avgjsstvxu.jpeg?q=70",
    title: "OrthoFlex Trainers",
    reviews: "(155 reviews)",
    prevPrice: "$145.00",
    newPrice: "125",
    company: "Vans",
    color: "green",
    category: "flats"
  },
  {
    id: 34,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/o/i/t/10-xo-soldier-12-blue-gry-10-fuel-blue-original-imah9zkmfqgcygks.jpeg?q=70",
    title: "FUEL",
    reviews: "(198 reviews)",
    prevPrice: "$100.00",
    newPrice: "70",
    company: "Adidas",
    color: "blue",
    category: "sandals"
  },
  {
    id: 35,
    img: "https://rukminim2.flixcart.com/image/612/612/kdnf98w0-0/shoe/r/l/9/cpm-10-city-soles-black-original-imafughcbk3zmfv8.jpeg?q=70",
    title: "City Soles",
    reviews: "(162 reviews)",
    prevPrice: "$180.00",
    newPrice: "145",
    company: "Puma",
    color: "black",
    category: "heels"
  },
  {
    id: 36,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/j/p/m/5-504-5-fashion-ride-red-original-imah6swkyfwyhk8z.jpeg?q=70",
    title: "Glamour Step",
    reviews: "(143 reviews)",
    prevPrice: "$170.00",
    newPrice: "135",
    company: "Nike",
    color: "red",
    category: "heels"
  },
  {
    id: 37,
    img: "https://rukminim2.flixcart.com/image/612/612/ki4w0i80-0/shoe/9/d/o/657-casualsss-navy-7-kzaara-navy-original-imafyy3jefqqrg2v.jpeg?q=70",
    title: "MotionMax Racer #37",
    reviews: "(153 reviews)",
    prevPrice: "$155.00",
    newPrice: "120",
    company: "Adidas",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 38,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/f/3/l/6-cross-patti-fookni-6-ravis-white-original-imah5f8f9zjpgswa.jpeg?q=70",
    title: "Lux Stiletto",
    reviews: "(210 reviews)",
    prevPrice: "$190.00",
    newPrice: "160",
    company: "Vans",
    color: "white",
    category: "heels"
  },
  {
    id: 40,
    img: "https://rukminim2.flixcart.com/image/612/612/ke1pnrk0-0/shoe/f/f/l/lg-1011-7-le-greem-black-original-imafutmgvzhh879u.jpeg?q=70",
    title: "LE GREEM",
    reviews: "(148 reviews)",
    prevPrice: "$150.00",
    newPrice: "120",
    company: "Nike",
    color: "black",
    category: "sneakers"
  },
  {
    id: 41,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/a/f/n/5-6715170-5-bata-red-original-imagrh2rtebezqgs.jpeg?q=70",
    title: "Women Heels Sandal",
    reviews: "(165 reviews)",
    prevPrice: "$140.00",
    newPrice: "115",
    company: "Nike",
    color: "red",
    category: "heels"
  },
  {
    id: 42,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/o/5/c/6-rng-eva-852-blk-6-skymore-black-original-imah2pbuq6nkmsjt.jpeg?q=70",
    title: "SKYMORE",
    reviews: "(110 reviews)",
    prevPrice: "$155.00",
    newPrice: "100",
    company: "Puma",
    color: "black",
    category: "heels"
  },
  {
    id: 43,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/l/a/h/9-c03-9-calibrel-green-original-imahbdacgqgvhvxg.jpeg?q=70",
    title: "Fresh Air Sandals",
    reviews: "(130 reviews)",
    prevPrice: "$120.00",
    newPrice: "85",
    company: "Vans",
    color: "green",
    category: "sandals"
  },
  {
    id: 44,
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Classic Walk",
    reviews: "(95 reviews)",
    prevPrice: "$105.00",
    newPrice: "70",
    company: "Nike",
    color: "blue",
    category: "flats"
  },
  {
    id: 45,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/p/e/o/8-overstar120-green-8-8-house-of-common-green-original-imahbgfjnyuuhn2w.jpeg?q=70",
    title: "Street Luxe",
    reviews: "(180 reviews)",
    prevPrice: "$165.00",
    newPrice: "130",
    company: "Adidas",
    color: "green",
    category: "sneakers"
  },
  {
    id: 46,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-shoe/q/o/j/6-spf-k-7048-bersache-black-original-imagp359mrb9xgcm.jpeg?q=70",
    title: "BERSACHE",
    reviews: "(215 reviews)",
    prevPrice: "$190.00",
    newPrice: "160",
    company: "Puma",
    color: "black",
    category: "heels"
  },
  {
    id: 48,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/0/h/2/7-l-194-twinsshoe-cherry-original-imahfhjkjgh8tvyr.jpeg?q=70",
    title: "Soft Glide",
    reviews: "(190 reviews)",
    prevPrice: "$180.00",
    newPrice: "145",
    company: "Adidas",
    color: "red",
    category: "flats"
  },
  {
    id: 49,
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Classic Steps",
    reviews: "(105 reviews)",
    prevPrice: "$125.00",
    newPrice: "95",
    company: "Vans",
    color: "blank",
    category: "flats"
  },
  {
    id: 50,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/j/b/0/5-2001-5-overstar-green-original-imahctyqnr2zrhku.jpeg?q=70",
    title: "Flight Runner",
    reviews: "(165 reviews)",
    prevPrice: "$150.00",
    newPrice: "125",
    company: "Nike",
    color: "green",
    category: "sneakers"
  },
  {
    id: 51,
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Speedster Pro #51",
    reviews: "(150 reviews)",
    prevPrice: "$170.00",
    newPrice: "140",
    company: "Adidas",
    color: "black",
    category: "sneakers"
  },
  {
    id: 52,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/z/w/1/5-151-red-42-combo-151-red-lovely-red-original-imahbvg9vmkfpazh.jpeg?q=70",
    title: "Luxe Flat Sandals",
    reviews: "(120 reviews)",
    prevPrice: "$180.00",
    newPrice: "130",
    company: "Puma",
    color: "red",
    category: "flats"
  },
  {
    id: 54,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/b/9/b/7-ak10001-blu-7-shoezy-white-original-imahbcyjxnkwutvq.jpeg?q=70",
    title: "Trail Runner",
    reviews: "(145 reviews)",
    prevPrice: "$140.00",
    newPrice: "115",
    company: "Nike",
    color: "green",
    category: "sneakers"
  },
  {
    id: 55,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/r/b/z/8-ori-z-9170-8-bersache-black-original-imah8ufkyg6sxuwz.jpeg?q=70",
    title: "BERSACHE",
    reviews: "(175 reviews)",
    prevPrice: "$190.00",
    newPrice: "155",
    company: "Adidas",
    color: "black",
    category: "heels"
  },
  {
    id: 59,
    img: "https://rukminim2.flixcart.com/image/612/612/kgiaykw0-0/shoe/h/l/e/lalit-444-8-believe-black-original-imafwqjgcgzgejmj.jpeg?q=70",
    title: "Power Boost",
    reviews: "(160 reviews)",
    prevPrice: "$140.00",
    newPrice: "120",
    company: "Adidas",
    color: "black",
    category: "sneakers"
  },
  {
    id: 60,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/l/i/p/4-1407wht-4-0-mosac-white-original-imahd77z8fdvwdpd.jpeg?q=70",
    title: "Classic Stepper",
    reviews: "(100 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Puma",
    color: "white",
    category: "heels"
  },
  {
    id: 61,
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Walk Easy",
    reviews: "(140 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Vans",
    color: "red",
    category: "flats"
  },
  {
    id: 63,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/d/e/i/9-leopard-heel-9-ravis-white-original-imah5f5nraktchyj.jpeg?q=70",
    title: "Chic Comfort",
    reviews: "(110 reviews)",
    prevPrice: "$130.00",
    newPrice: "100",
    company: "Adidas",
    color: "white",
    category: "heels"
  },
  {
    id: 64,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/s/l/w/8-dl-k-07-cherry-8-deera-cherry-original-imahddkmr9qnffbz.jpeg?q=70",
    title: "Modern Stilettos",
    reviews: "(190 reviews)",
    prevPrice: "$180.00",
    newPrice: "160",
    company: "Puma",
    color: "red",
    category: "flats"
  },
  {
    id: 66,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/0/j/0/8-hoc-combo-fk-5408-5422-42-house-of-common-blue-original-imahd6ym3fz5x5y6.jpeg?q=70",
    title: "Rapid Runner",
    reviews: "(200 reviews)",
    prevPrice: "$165.00",
    newPrice: "140",
    company: "Nike",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 68,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/h/u/0/-original-imahfqy34negvwfq.jpeg?q=70",
    title: "RS-XK X Sneakers For Men",
    reviews: "(120 reviews)",
    prevPrice: "$115.00",
    newPrice: "90",
    company: "Puma",
    color: "black",
    category: "flats"
  },
  {
    id: 69,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/w/t/m/4-mehrooncombo-029-4-doctor-extra-soft-mehroon-original-imahy3zpkjwgwyh8.jpeg?q=70",
    title: "Sprint Pro",
    reviews: "(130 reviews)",
    prevPrice: "$140.00",
    newPrice: "110",
    company: "Vans",
    color: "red",
    category: "flats"
  },
  {
    id: 71,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/x/f/y/9-hoc-combo-fk-5412-5420-43-house-of-common-white-original-imahd6ymc45vggjt.jpeg?q=70",
    title: "Velocity Runner",
    reviews: "(190 reviews)",
    prevPrice: "$155.00",
    newPrice: "135",
    company: "Adidas",
    color: "white",
    category: "sneakers"
  },
  {
    id: 72,
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Elegance Flats",
    reviews: "(120 reviews)",
    prevPrice: "$140.00",
    newPrice: "115",
    company: "Puma",
    color: "black",
    category: "flats"
  },
  {
    id: 73,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/r/v/5/5-156-purpal-41-combo-151-red-lovely-red-original-imahbjkkqtsahf5g.jpeg?q=70",
    title: "Sprint",
    reviews: "(165 reviews)",
    prevPrice: "$130.00",
    newPrice: "110",
    company: "Vans",
    color: "red",
    category: "flats"
  },
  {
    id: 74,
    img: "https://rukminim2.flixcart.com/image/612/612/kgl5ua80-0/shoe/c/8/7/786-casuals-black-10-kaneggye-navy-original-imafws94pxmgss9p.jpeg?q=70",
    title: "Power Glide",
    reviews: "(200 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Nike",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 75,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/6/q/6/8-394371-puma-black-matte-silver-original-imaghkpenkhn6ahn.jpeg?q=70",
    title: "Classic Step",
    reviews: "(140 reviews)",
    prevPrice: "$135.00",
    newPrice: "110",
    company: "Adidas",
    color: "black",
    category: "heels"
  },
  {
    id: 76,
    img: "https://rukminim2.flixcart.com/image/612/612/khdqnbk0/shoe/9/p/8/sqartertyutarera-6-kzaara-mehandi-original-imafxepfvba4wuwa.jpeg?q=70",
    title: "Runner Pro",
    reviews: "(180 reviews)",
    prevPrice: "$145.00",
    newPrice: "130",
    company: "Puma",
    color: "green",
    category: "sneakers"
  },
  {
    id: 77,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/7/w/k/9-samosa-9-ravis-white-original-imah5f7x6rf43y9v.jpeg?q=70",
    title: "Comfort Walk",
    reviews: "(150 reviews)",
    prevPrice: "$120.00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats"
  },
  {
    id: 78,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/i/a/f/10-m9696c-10-converse-red-original-imahaxfvcch3wm6m.jpeg?q=70",
    title: "Trail Blaze",
    reviews: "(170 reviews)",
    prevPrice: "$155.00",
    newPrice: "140",
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    id: 79,
    img: "https://rukminim2.flixcart.com/image/612/612/kuvkcy80/shoe/d/l/l/7-dotrpdx003-rapidbox-blue-original-imag7wevbbzq2twt.jpeg?q=70",
    title: "Glam Stilettos #79",
    reviews: "(130 reviews)",
    prevPrice: "$180.00",
    newPrice: "160",
    company: "Adidas",
    color: "blue",
    category: "heels"
  },
  {
    id: 80,
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Easy Loafers",
    reviews: "(145 reviews)",
    prevPrice: "$140.00",
    newPrice: "120",
    company: "Puma",
    color: "red",
    category: "flats"
  },
  {
    id: 81,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/t/a/1/7-svr9261kbrv-7-svaar-aqua-blue-original-imahbkdrfq5z27fd.jpeg?q=70",
    title: "Men Clogs Sandal",
    reviews: "(160 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Vans",
    color: "blue",
    category: "sandals"
  },
  {
    id: 82,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/j/n/k/8-casual-24512-8-nobelite-white-red-original-imahdyz7pyyjfrd6.jpeg?q=70",
    title: "Flight Runner",
    reviews: "(185 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Nike",
    color: "white",
    category: "sneakers"
  },
  {
    id: 83,
    img: "https://rukminim2.flixcart.com/image/612/612/k7usyvk0/shoe/2/p/v/8215088-5-bata-red-original-imafqydbabfyfdht.jpeg?q=70",
    title: "Stiletto Edge",
    reviews: "(140 reviews)",
    prevPrice: "$170.00",
    newPrice: "150",
    company: "Adidas",
    color: "red",
    category: "sneakers"
  },
  {
    id: 84,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/v/w/f/10-27602084-10-hrx-by-hrithik-roshan-bruklyn-t-blue-original-imahc9tff8rjwwap.jpeg?q=70",
    title: "Classic Sneakers",
    reviews: "(190 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Puma",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 85,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/w/u/m/10-556-labbin-black-original-imagmr3nejupk7ph.jpeg?q=70",
    title: "Casual Sneaker",
    reviews: "(135 reviews)",
    prevPrice: "$115.00",
    newPrice: "90",
    company: "Vans",
    color: "black",
    category: "flats"
  },
  {
    id: 86,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/3/c/b/-original-imah4zhsfzgucudg.jpeg?q=70",
    title: "Power Glide",
    reviews: "(160 reviews)",
    prevPrice: "$155.00",
    newPrice: "130",
    company: "Nike",
    color: "white",
    category: "sneakers"
  },
  {
    id: 87,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/f/t/2/8-abf-005-41-ak-sky-white-original-imah9pdmvqyjm2xj.jpeg?q=70",
    title: "Speed Loafers",
    reviews: "(120 reviews)",
    prevPrice: "$140.00",
    newPrice: "110",
    company: "Adidas",
    color: "white",
    category: "flats"
  },
  {
    id: 88,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/2/p/f/6-hv-15802-red-6-harvard-red-original-imagkf5kqmyfpbrt.jpeg?q=70",
    title: "Trail Runner",
    reviews: "(200 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Puma",
    color: "red",
    category: "sneakers"
  },
  {
    id: 89,
    img: "https://rukminim2.flixcart.com/image/612/612/kgtqhe80-0/shoe/d/a/m/myk-sneakers-7-kzaara-red-original-imafwz9fy6keq3yx.jpeg?q=70",
    title: "Glam Stilettos",
    reviews: "(180 reviews)",
    prevPrice: "$170.00",
    newPrice: "150",
    company: "Vans",
    color: "red",
    category: "sneakers"
  },
  {
    id: 91,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/6/g/s/9-hrxecsp576-9-hrx-by-hrithik-roshan-white-blue-original-imahcsvunz5uqjgw.jpeg?q=70",
    title: "Stride Flex",
    reviews: "(178 reviews)",
    prevPrice: "$165.00",
    newPrice: "140",
    company: "Adidas",
    color: "white",
    category: "sneakers"
  },
  {
    id: 92,
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Smooth Walk",
    reviews: "(140 reviews)",
    prevPrice: "$130.00",
    newPrice: "115",
    company: "Puma",
    color: "black",
    category: "flats"
  },
  {
    id: 93,
    img: "https://rukminim2.flixcart.com/image/612/612/k6fd47k0pkrrdj/shoe/z/c/g/6-fppmsgcomk-kraven-original-imafzmdc2wbhp2m9.jpeg?q=70",
    title: "Speed Glide",
    reviews: "(160 reviews)",
    prevPrice: "$140.00",
    newPrice: "120",
    company: "Vans",
    color: "red",
    category: "sneakers"
  },
  {
    id: 94,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/x/p/k/7-bis-snk-eva-851-blu-7-bruton-blue-original-imahbch75zuzxgr8.jpeg?q=70",
    title: "Trail Runner #94",
    reviews: "(190 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Nike",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 95,
    img: "https://rukminim2.flixcart.com/image/612/612/kgl5ua80-0/shoe/p/h/l/658-casualss-black-10-kaneggye-black-original-imafwsagdzruf83z.jpeg?q=70",
    title: "Classic Loafers",
    reviews: "(145 reviews)",
    prevPrice: "$135.00",
    newPrice: "110",
    company: "Adidas",
    color: "black",
    category: "heels"
  },
  {
    id: 96,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/x/q/e/7-1001-green-eos-7-noak-green-original-imah4rvdaapnqgc4.jpeg?q=70",
    title: "Flex Sprint",
    reviews: "(180 reviews)",
    prevPrice: "$145.00",
    newPrice: "130",
    company: "Puma",
    color: "green",
    category: "sneakers"
  },
  {
    id: 97,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/8/w/j/5-r55-madam-glorious-white-original-imagvrbyyjxp2hdy.jpeg?q=70",
    title: "Comfy Step",
    reviews: "(150 reviews)",
    prevPrice: "$120.00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats"
  },
  {
    id: 98,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/o/8/p/10-12410312-ruosh-red-original-imagxqhwhmq58ujh.jpeg?q=70",
    title: "Speed Blaze",
    reviews: "(170 reviews)",
    prevPrice: "$155.00",
    newPrice: "140",
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    id: 99,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/b/z/5/7-snk-2cmb-2031-fitman-41-bruton-blue-red-original-imagganmkyfx8dfb.jpeg?q=70",
    title: "Glamour Heels",
    reviews: "(130 reviews)",
    prevPrice: "$180.00",
    newPrice: "160",
    company: "Adidas",
    color: "blue",
    category: "heels"
  },
  {
    id: 100,
    img: "https://rukminim2.flixcart.com/image/612/612/kb1470w0/sandal/c/f/h/53000853052-7-khadim-s-red-original-imafshyvcdq2x9hw.jpeg?q=70",
    title: "Easy Loafers",
    reviews: "(145 reviews)",
    prevPrice: "$140.00",
    newPrice: "120",
    company: "Puma",
    color: "red",
    category: "flats"
  },
  {
    id: 101,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/h/i/6/7-litewalknr-liberty-green-original-imaha7guhpwjbpzg.jpeg?q=70",
    title: "Men Clogs Sandal",
    reviews: "(160 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Vans",
    color: "green",
    category: "sandals"
  },
  {
    id: 102,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/o/2/b/8-e-active-01-white-lakhani-aashirwad-white-original-imah459knutdx3nc.jpeg?q=70",
    title: "Flight Glide",
    reviews: "(185 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Nike",
    color: "white",
    category: "sneakers"
  },
  {
    id: 103,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/f/h/b/4-150-pnk-42-combo-151-red-lovely-red-original-imahbjkkts34uagf.jpeg?q=70",
    title: "Stiletto Edge",
    reviews: "(140 reviews)",
    prevPrice: "$170.00",
    newPrice: "150",
    company: "Adidas",
    color: "red",
    category: "flats"
  },
  {
    id: 105,
    img: "https://rukminim2.flixcart.com/image/612/612/kzx1a4w0/shoe/n/r/d/8-lksdn-8-kzaara-black-original-imagbtfz5yc3vvbq.jpeg?q=70",
    title: "Casual Flats #105",
    reviews: "(135 reviews)",
    prevPrice: "$115.00",
    newPrice: "90",
    company: "Vans",
    color: "black",
    category: "flats"
  },
  {
    id: 106,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/s/x/y/7-wht1716-7-erix-white-original-imagnqfnfffnnxqx.jpeg?q=70",
    title: "Power Glide",
    reviews: "(160 reviews)",
    prevPrice: "$155.00",
    newPrice: "130",
    company: "Nike",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 107,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/m/e/t/5-article-0120005-white-flat-ssv-white-original-imah2rrzuwyegzqu.jpeg?q=70",
    title: "Speed Loafers",
    reviews: "(120 reviews)",
    prevPrice: "$140.00",
    newPrice: "110",
    company: "Adidas",
    color: "white",
    category: "flats"
  },
  {
    id: 108,
    img: "https://rukminim2.flixcart.com/image/612/612/km57hjk0/sandal/q/9/e/4-sswf-003-4-sosu-red-original-imagf3x4dhzdvzhf.jpeg?q=70",
    title: "Trail Runner",
    reviews: "(200 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Puma",
    color: "red",
    category: "flats"
  },
  {
    id: 109,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/m/f/u/7-new-601-sosu-red-original-imaggddqefdujmbk.jpeg?q=70",
    title: "Glam Stilettos",
    reviews: "(180 reviews)",
    prevPrice: "$170.00",
    newPrice: "150",
    company: "Vans",
    color: "red",
    category: "flats"
  },
  {
    id: 110,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/a/l/j/10-s048-10-semana-green-original-imagh6czezm95shq.jpeg?q=70",
    title: "Easy Runner",
    reviews: "(150 reviews)",
    prevPrice: "$140.00",
    newPrice: "120",
    company: "Nike",
    color: "green",
    category: "sneakers"
  },
  {
    id: 111,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/b/k/x/6-dic1503-6-dicy-blue-original-imagsyvfk3fwyhnc.jpeg?q=70",
    title: "Elegant Steps",
    reviews: "(140 reviews)",
    prevPrice: "$165.00",
    newPrice: "140",
    company: "Adidas",
    color: "blue",
    category: "heels"
  },
  {
    id: 112,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/6/j/b/-original-imahbxh8jbfkzveh.jpeg?q=70",
    title: "Street Sprint",
    reviews: "(160 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Puma",
    color: "white",
    category: "sneakers"
  },
  {
    id: 114,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/o/o/6/7-as-1003-red-wht-action-milano-red-white-original-imah568gnnzz3agz.jpeg?q=70",
    title: "Power Glide",
    reviews: "(130 reviews)",
    prevPrice: "$140.00",
    newPrice: "120",
    company: "Vans",
    color: "red",
    category: "sneakers"
  },
  {
    id: 117,
    img: "https://rukminim2.flixcart.com/image/612/612/ktyp8cw0/sandal/s/p/8/9-lr1211-red-43-shezone-red-original-imag76nbwzh4tazv.jpeg?q=70",
    title: "Trail Edge",
    reviews: "(190 reviews)",
    prevPrice: "$165.00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "flats"
  },
  {
    id: 118,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/n/q/r/8-b-1604-8-lovehush-blue-original-imah2fhxqhnbgsh7.jpeg?q=70",
    title: "Casual Walk #118",
    reviews: "(160 reviews)",
    prevPrice: "$145.00",
    newPrice: "130",
    company: "Vans",
    color: "blue",
    category: "flats"
  },
  {
    id: 119,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/b/9/b/7-ak10001-blu-7-shoezy-white-original-imahbcyjxnkwutvq.jpeg?q=70",
    title: "Swift Step",
    reviews: "(175 reviews)",
    prevPrice: "$155.00",
    newPrice: "140",
    company: "Nike",
    color: "green",
    category: "sneakers"
  },
  {
    id: 121,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/u/r/h/7-article-020007-ssv-white-original-imaguhmg2zbzjqr6.jpeg?q=70",
    title: "Casual Flex",
    reviews: "(160 reviews)",
    prevPrice: "$145.00",
    newPrice: "130",
    company: "Puma",
    color: "white",
    category: "flats"
  },
  {
    id: 122,
    img: "https://rukminim2.flixcart.com/image/612/612/kuvkcy80/sandal/m/h/l/4-92-10377-mordant-red-maeve-shelby-red-original-imag7whezmj4fbr2.jpeg?q=70",
    title: "Power Runner",
    reviews: "(180 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Vans",
    color: "red",
    category: "flats"
  },
  {
    id: 123,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/f/i/6/6-dash-white-black-sky-6-6-club-style-white-original-imahbep4hx7da5nx.jpeg?q=70",
    title: "Speed Stiletto",
    reviews: "(150 reviews)",
    prevPrice: "$155.00",
    newPrice: "130",
    company: "Nike",
    color: "blue",
    category: "heels"
  },
  {
    id: 124,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/9/w/w/3-a-27-grn-3-3-0-zuliet-collection-green-original-imahbagvafzkxrrk.jpeg?q=70",
    title: "Comfy Step",
    reviews: "(140 reviews)",
    prevPrice: "$140.00",
    newPrice: "120",
    company: "Adidas",
    color: "green",
    category: "heels"
  },
  {
    id: 125,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/p/u/j/12-k202-12-killer-black-original-imahbk9khvazjfmu.jpeg?q=70",
    title: "Lightweight Comfort",
    reviews: "(170 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Puma",
    color: "black",
    category: "sneakers"
  },
  {
    id: 126,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/z/a/l/6-ml050106-marc-loire-cream-original-imahbdgajtyvygzd.jpeg?q=70",
    title: "Classic Flex",
    reviews: "(180 reviews)",
    prevPrice: "$165.00",
    newPrice: "140",
    company: "Vans",
    color: "white",
    category: "flats"
  },
  {
    id: 127,
    img: "https://rukminim2.flixcart.com/image/612/612/kx9as280/sandal/y/c/h/4-93-11245-red-4-maeve-shelby-red-original-imag9r84h8zyqzjy.jpeg?q=70",
    title: "Trail Runner",
    reviews: "(160 reviews)",
    prevPrice: "$155.00",
    newPrice: "130",
    company: "Nike",
    color: "red",
    category: "flats"
  },
  {
    id: 128,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/y/f/d/sl01-10-amico-black-original-imafhxthct3t65wv-bb.jpeg?q=70",
    title: "Men Casual Sandals",
    reviews: "(140 reviews)",
    prevPrice: "$140.00",
    newPrice: "120",
    company: "Adidas",
    color: "black",
    category: "sandals"
  },
  {
    id: 129,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/9/e/j/6-ori-z-9163-6-bersache-blue-original-imah8ufjy2jfs2p7.jpeg?q=70",
    title: "Urban Runner",
    reviews: "(130 reviews)",
    prevPrice: "$130.00",
    newPrice: "110",
    company: "Puma",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 130,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/z/s/k/3-33-3151-36-metro-89-dark-beige-original-imagh3zs7eh48cgy.jpeg?q=70",
    title: "Power Walk",
    reviews: "(120 reviews)",
    prevPrice: "$125.00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats"
  },
  {
    id: 131,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/b/3/a/5-d126b38-dressberry-white-original-imah9r3mf8v8kphe.jpeg?q=70",
    title: "Dressberry",
    reviews: "(120 reviews)",
    prevPrice: "$125.00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats"
  },
  {
    id: 143,
    img: "https://rukminim2.flixcart.com/image/612/612/ku4ezrk0/sandal/g/y/y/6-92-10212-red-maeve-shelby-red-original-imag7bghgd2ky6pj.jpeg?q=70",
    title: "Urban Style",
    reviews: "(170 reviews)",
    prevPrice: "$160.00",
    newPrice: "140",
    company: "Adidas",
    color: "red",
    category: "flats"
  },
  {
    id: 144,
    img: "https://rukminim2.flixcart.com/image/612/612/kklhbbk0/shoe/g/v/2/6-530-mocassin-6-kzaara-blue-original-imafzwhcg8gcda3m.jpeg?q=70",
    title: "Sprint Flex",
    reviews: "(110 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Vans",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 145,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/a/c/1/6-6sbzhl217-new1-tryme-green-original-imagxfg5zzfzgks3.jpeg?q=70",
    title: "Glide Pro",
    reviews: "(140 reviews)",
    prevPrice: "$155.00",
    newPrice: "135",
    company: "Puma",
    color: "green",
    category: "heels"
  },
  {
    id: 146,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/z/y/7/13-bbmh9100-13-bacca-bucci-white-original-imah39catxwtghx4.jpeg?q=70",
    title: "Street Runner",
    reviews: "(130 reviews)",
    prevPrice: "$160.00",
    newPrice: "150",
    company: "Nike",
    color: "white",
    category: "sneakers"
  },
  {
    id: 148,
    img: "https://rukminim2.flixcart.com/image/612/612/kt0enww0/sandal/r/9/r/4-doc26-4-denill-cherry-original-imag6ghshd26zybh.jpeg?q=70",
    title: "Flex Run",
    reviews: "(120 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Vans",
    color: "red",
    category: "flats"
  },
  {
    id: 149,
    img: "https://rukminim2.flixcart.com/image/612/612/kura1e80/shoe/x/c/l/7-brd-566-brd-574-7-birde-multicolor-original-imag7t6wyttzrhjw.jpeg?q=70",
    title: "Urban Glide",
    reviews: "(135 reviews)",
    prevPrice: "$145.00",
    newPrice: "125",
    company: "Puma",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 150,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/c/b/s/5-cross-patti-fookni-5-ravis-green-original-imah5f89wzuvqsqw.jpeg?q=70",
    title: "Trail Runner",
    reviews: "(140 reviews)",
    prevPrice: "$155.00",
    newPrice: "140",
    company: "Nike",
    color: "green",
    category: "heels"
  },
  {
    id: 151,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/8/h/y/6-8716278-6-bata-black-original-imahb5w9npakkrsj.jpeg?q=70",
    title: "Casual Sandals",
    reviews: "(110 reviews)",
    prevPrice: "$130.00",
    newPrice: "115",
    company: "Adidas",
    color: "black",
    category: "sandals"
  },
  {
    id: 153,
    img: "https://rukminim2.flixcart.com/image/612/612/l0sgyvk0/sandal/v/q/z/3-sswf-003-six6-red-original-imagchh5n7g2xc6g.jpeg?q=70",
    title: "Urban Walk",
    reviews: "(120 reviews)",
    prevPrice: "$125.00",
    newPrice: "110",
    company: "Vans",
    color: "red",
    category: "flats"
  },
  {
    id: 154,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/f/n/q/6-1008-blue1-6-house-of-common-blue-original-imahbzgjtdnwmfht.jpeg?q=70",
    title: "Street Pro",
    reviews: "(115 reviews)",
    prevPrice: "$145.00",
    newPrice: "130",
    company: "Nike",
    color: "blue",
    category: "sneakers"
  },
  {
    id: 155,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/9/w/w/3-a-27-grn-3-3-0-zuliet-collection-green-original-imahbagvafzkxrrk.jpeg?q=70",
    title: "Flex Comfort",
    reviews: "(130 reviews)",
    prevPrice: "$135.00",
    newPrice: "120",
    company: "Adidas",
    color: "green",
    category: "heels"
  },
  {
    id: 156,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/x/c/o/10-marble-white-9-leecook-white-original-imahcz4jdnwngnng.jpeg?q=70",
    title: "Men Clogs Sandal",
    reviews: "(140 reviews)",
    prevPrice: "$150.00",
    newPrice: "140",
    company: "Puma",
    color: "white",
    category: "sandals"
  },
  {
    id: 158,
    img: "https://rukminim2.flixcart.com/image/612/612/ksxjs7k0hlty2aw/women-footwear/d/p/8/-original-imag6kf2abjbpumt.jpeg?q=70",
    title: "Slide Comfort",
    reviews: "(125 reviews)",
    prevPrice: "$120.00",
    newPrice: "110",
    company: "Nike",
    color: "red",
    category: "flats"
  },
  {
    id: 159,
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/v/m/h/6-937-6-pu-pine-black-original-imahd9bgsakfhegq.jpeg?q=70",
    title: "Trail Blazer",
    reviews: "(100 reviews)",
    prevPrice: "$130.00",
    newPrice: "115",
    company: "Adidas",
    color: "black",
    category: "sandals"
  },
  {
    id: 160,
    img: "https://rukminim2.flixcart.com/image/612/612/kqidx8w0/slipper-flip-flop/e/w/3/3-patentbucklerubbergola1-shoe-lab-black-original-imag4g3tghvggrhz.jpeg?q=70",
    title: "Urban Classic",
    reviews: "(140 reviews)",
    prevPrice: "$140.00",
    newPrice: "130",
    company: "Puma",
    color: "red",
    category: "flats"
  }
];

export default data;
